version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      - POSTGRES_DB=techShopProgra
      - POSTGRES_USER=daniel
      - POSTGRES_PASSWORD=12345
    networks:
      - red
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "collaguazodaniel48@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "88:80"
    depends_on:
      - postgres
    networks:
      - red

  techshop_api:
    image: techshop_api
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      JAEGER_SERVICE_NAME: jaeger
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    depends_on:
      - postgres
    networks:
      - red

  techshop_front:
    image: techshop_front
    ports: 
      - "4200:80"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /rest/openapi.yaml
    volumes:   
      - ./openapi.yaml:/rest/openapi.yaml
    networks:
      - red

  jaeger:
    image: jaegertracing/all-in-one:1.16.0
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    depends_on:
      - techshop_api
    networks:
      - red
networks:
  red: